---
title: "Internal Factors Model"
author: "Skyler Crouch"
date: "2025-04-04"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(coda)
```

```{r}
## load site data
site_data <- readr::read_csv("https://raw.githubusercontent.com/eco4cast/neon4cast-targets/main/NEON_Field_Site_Metadata_20220412.csv") |> 
  dplyr::filter(ticks == 1)
tall_data <- site_data[8, ]

# tick data
ticks_data <- readr::read_csv("https://data.ecoforecast.org/neon4cast-targets/ticks/ticks-targets.csv.gz", guess_max = 1e6)
TALL_ticks <- ticks_data[ticks_data$site_id == 'TALL',]
```

```{r}
## internal factors model
tall_internal <- "
model{

  ## Prior for the initial state on the count scale
  X[1] ~ dnorm(x_ic, tau_ic)
  
  ## Prior for process error precision (tau_proc)
  tau_proc ~ dgamma(0.1, 0.1)
  
  ## Priors for internal process parameters
  r ~ dnorm(0.1, 0.1)            # Intrinsic growth rate
  K ~ dnorm(0, 0.1) T(0,)         # Carrying capacity
  
  ## Set initial process mean
  u_tc[1] <- X[1]
  
  ## Process model: logistic growth with process error
  for(i in 2:Ni){
    E[i] ~ dnorm(0, tau_proc)                                  
    u_tc[i] <- r * X[i-1] * (1 - (X[i-1] / K)) + E[i]            
    X[i] <- u_tc[i]                                            
  }
  
  ## Data model: Observations are drawn from a Poisson distribution
  for(i in 1:Ni){
    y[i] ~ dpois(max(0.001, u_tc[i]))
  }
}
"
```

```{r}
## specify initial values
nchain <- 3
inits <- list()
for(i in 1:nchain){
  inits[[i]] <- list(
    r = 0.1,           # initial guess for intrinsic growth rate
    K = 1000,          # initial guess for carrying capacity
    tau_proc = 1       # initial value for process error precision
  )
}
```

```{r}
## data list for jags
data <- list(
  y = round(TALL_ticks$observation),     
  Ni = length(TALL_ticks$observation),   
  x_ic = 63,         #initial conditions seat around the tick count mean
  tau_ic = 100       
)
```

```{r}
## run jags with the specified initial values
jags_model <- jags.model(file = textConnection(tall_internal),
                         data = data,
                         inits = inits,
                         n.chains = nchain,
                         n.adapt = 500)

jags.out <- coda.samples(model = jags_model,
                         variable.names = c("r", "K", "X", "tau_proc"),
                         n.iter = 20000)
```

```{r}
# Plot the MCMC results and diagnostics
par(mar = c(4, 4, 2, 2))
plot(jags.out)
gelman.diag(jags.out)
## Note: Some parameters, including r and process error precision, are showing convergence issues. I've increased the number of iterations quite a bit, but it hasn't made a difference. I have a few thoughts as to why: 1) the logistic growth model inherently involves parameters that can be highly correlated; 2) the limited range and variability in the tick data provide insufficient information for precise estimation of r and Tau_proc; 3) the model may require more informative priors to stabilize the estimation process.
```